[build]
  base = "app"
  command = "npm run build"
  publish = "dist"

[functions]
  # Keďže base je "app", cesta k funkciám je teraz priamo v ňom
  directory = "netlify/functions"

[functions.node_bundle]
  external_node_modules = ["playwright-core", "chromium-bidi", "axe-core"]
  on_error = "continue"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"