[build]
  base = "app"
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "../netlify/functions"

[functions.node_version]
  version = "18"
  external_node_modules = ["playwright", "axe-core"]
