[build]
  base = "app"
  command = "npm run build"
  publish = "dist"

[functions]
  # Cesta je relatívna k 'base', takže 'app/netlify/functions'
  directory = "netlify/functions"
  node_bundler = "esbuild"
  timeout = 90

[functions.node_bundle]
  # Zoznam všetkých modulov, ktoré majú zostať nedotknuté
  external_node_modules = ["playwright-core", "@sparticuz/chromium-min", "axe-core", "chromium-bidi"]
  on_error = "continue"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"