[build]
  base = ""
  command = "npm install && npm run build --prefix app"
  publish = "app/dist"

[functions]
  directory = "netlify/functions"
  # Sem už nepíš node_bundle = true, definujeme to priamo nižšie

  [functions.node_bundle]
    external_node_modules = ["playwright-core", "chromium-bidi", "axe-core"]

[dev]
  command = "npm run dev --prefix app"
  port = 8888
  targetPort = 5173