[build]
  base = "app"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.node_bundle]
  # Týmto povieme esbuildu, aby Playwright nebol externý, 
  # ale aby ho vbalil PRIAMO do jedného súboru s tvojou funkciou.
  # Tým zmiznú tie nešťastné require cesty.
  external_node_modules = ["@sparticuz/chromium-min"]

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"