[build]
  base = "app"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Presunul som timeout sem, mal by byť braný ako číslo
  timeout = 90

[functions.node_bundle]
  external_node_modules = ["playwright-core", "@sparticuz/chromium-min", "axe-core", "chromium-bidi"]
  on_error = "continue"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"